jobs:
  fake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ocaml-variants.4.14.0+options,ocaml-option-musl,ocaml-option-static
          opam-pin: false
      - run: sudo apt-get update
      - run: opam install --depext-only conf-pkg-config conf-libpcre conf-libpcre2-8 conf-gmp conf-libev conf-libcurl
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - run: opam install .

name: work
on:
  pull_request: null
  push:
    branches:
      - main
  workflow_dispatch: null
